### PR TITLE
Fork Sync: Update from parent repository

### PR DESCRIPTION
**Pull request by JustusW**

### CODE REVIEW

**Review by JustusW — COMMENTED** [review]
Auto approved

**Comment by fsamareanu** [comment]
Hello,

Is automatic build failing? Latest release is from 29th. Thank you for your time doing this.

**Comment by JustusW** [comment]
> Is automatic build failing? Latest release is from 29th. Thank you for your time doing this.

Sadly the author has stopped tagging releases on GitHub. I assume that was intentional and while it is on the petty side I won't overrule his decision to not honor the GPL.

**Comment by fsamareanu** [comment]
Latest release for Retail is June 9th so probably that's the explanation. I just checked.

**Comment by JustusW** [comment]
I just did a manual release. Poke me if something is wrong.

**Pull request merged**
